server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/test
    password: root
  jpa:
    hibernate:
      ddL-auto: update
    show-sql: 'true'